### ISSUE TITLE
[Bug]: cm so dalao

### ISSUE THREAD

**Issue by AWeirdDev** [LittleCow-moo/didi#3]
### Email 聯繫

aweirdscratcher@gmail.com

### 回報或建議

u sushi baka

### 您的系統

Windows

### 主控台

```shell
Cm so dalao
```

### 勾選部分

- [x] 從來沒有人回報過此錯誤
- [x] 牛弟弟很可愛

**Comment by AWeirdDev** [comment]
Cm so dalao 🛐

**Comment by charlie-moomoo** [comment]
NOU

AWeirdDev ***@***.***> 於 2022年6月2日 週四 14:04 寫道：
